# Generated by Django 4.1.1 on 2022-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Enter 11 digits phone number', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
