# Generated by Django 4.1.1 on 2022-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_city_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
