# Generated by Django 4.1.1 on 2022-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
