# Generated by Django 4.1.1 on 2022-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api',
            field=models.CharField(max_length=250),
        ),
    ]
