# Generated by Django 4.1.1 on 2022-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_api_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='username',
        ),
        migrations.AlterField(
            model_name='api',
            name='api',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
