# Generated by Django 4.1.1 on 2022-10-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_api_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='username',
            new_name='user',
        ),
    ]
