# Generated by Django 4.1.1 on 2022-10-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_api_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='user',
        ),
    ]
